### ISSUE TITLE
`tb.sh deploy skl` fails every time

### ISSUE THREAD

**Issue by SergiiDmytruk** [3mdeb/meta-trenchboot#37]
Apparently it removes build artifacts before trying to deploy them.  I don't see how (the script seems to not do anything like that), but files do disappear and I get:

```
rsync: [sender] change_dir ".../yocto/build/tmp/work/core2-64-tb-linux/skl/git/image" failed: No such file or directory (2)
```

Using `scp` for deploying works fine, so this is not a big deal (just copy one file), but looks weird.

**Comment by m-iwanicki** [comment]
It's this line fault https://github.com/3mdeb/meta-trenchboot/blob/9a1d7d116865961403acfe023426d57509470236/scripts/tb.sh#L246

I'm not sure why but `bitbake -s` removes `skl` recipe:

```
Loading cache...done.
Loaded 4860 entries from dependency cache.
Removing 1 recipes from the core2-64 sysroot...done.
Removing 1 recipes from the genericx86_64 sysroot...done.
```

From what I can see it doesn't happen to grub.

**Comment by m-iwanicki** [comment]
@SergiiDmytruk This PR should fix this: https://github.com/3mdeb/meta-trenchboot/pull/38

I use `devtool` instead of `bitbake` to check current recipe version
