### ISSUE TITLE
`kas-generic-tb.yml` build is broken

### ISSUE THREAD

**Issue by SergiiDmytruk** [3mdeb/meta-trenchboot#44]
Addition of files under `recipes-extended/xen` by https://github.com/3mdeb/meta-trenchboot/pull/41 somehow breaks generic image.  Following [build instructions](https://github.com/3mdeb/meta-trenchboot?tab=readme-ov-file#build) results in:

```
ERROR: ParseError at /repo/recipes-extended/xen/xen-tools_tb.bb:5: Could not include required file recipes-extended/xen/xen.inc#########################                                                                                        | ETA:  0:00:04
ERROR: Parsing halted due to errors, see error messages above
```

At the same time `kas-container build meta-trenchboot/kas-xen-tb.yml` starts the build without issues.

Removing those new files helps, but that's not a solution.  Should they be somehow excluded from generic image?

**Comment by macpijan** [comment]
We can have a single image with both Linux and Xen at the same time, selectable via GRUB menu entries.
Does that work for you, or you prefer to have a Linux-only image as well?

**Comment by SergiiDmytruk** [comment]
> We can have a single image with both Linux and Xen at the same time, selectable via GRUB menu entries.

The Xen one?  Then shouldn't it be called generic?

> Does that work for you, or you prefer to have a Linux-only image as well?

I don't really care, it's just that there are 2 of them now, one of which doesn't work and the non-working one is used in the README and by `tb.sh`.

**Comment by krystian-hebel** [comment]
I can confirm that this error exists. Then again, #45 also doesn't build with instructions from README (`kas-container build meta-trenchboot/kas-generic-tb.yml`):

```
| cat: extra_deps.lst: No such file or directory
| make[3]: *** [Makefile:51924: syminfo.lst] Error 1
| make[3]: *** Waiting for unfinished jobs....
| make[3]: Leaving directory '/build/tmp/work/core2-64-tb-linux/grub/2.06/build/grub-core'
| make[2]: *** [Makefile:29254: all] Error 2
| make[2]: Leaving directory '/build/tmp/work/core2-64-tb-linux/grub/2.06/build/grub-core'
| make[1]: *** [Makefile:12079: all-recursive] Error 1
| make[1]: Leaving directory '/build/tmp/work/core2-64-tb-linux/grub/2.06/build'
| make: *** [Makefile:3888: all] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/work/poky/meta/recipes-bsp/grub/grub_2.12.bb:do_compile) failed with exit code '1'
```

**Comment by macpijan** [comment]
Can you please try building https://github.com/3mdeb/meta-trenchboot/blob/master/kas-xen-tb.yml ? If that would be sufficient for you, I would leave just one image, containing both Linux and Xen.

**Comment by krystian-hebel** [comment]
`kas-xen-tb.yml` on master builds, so documentation should be updated and non-working `kas-generic-tb.yml` either fixed or removed.

---

Is there a reason why [QEMU is included in the image](https://github.com/3mdeb/meta-trenchboot/blob/amd/recipes-extended/images/tb-xen-image.bb#L23)? It is heavy and slow to build.

**Comment by macpijan** [comment]
> Is there a reason why [QEMU is included in the image](https://github.com/3mdeb/meta-trenchboot/blob/amd/recipes-extended/images/tb-xen-image.bb#L23)? It is heavy and slow to build.

This follows upstream recipe for Xen image https://git.yoctoproject.org/meta-virtualization/tree/recipes-extended/images/xen-image-minimal.bb#n16

I guess we could drop it, at least right now, if we do not need it.

**Comment by macpijan** [comment]
I am glad to head that the `kas-xen-tb.yml` works for you for the moment. I will submit a PR later on to fix the documentation, and potentially, remove the second image as well.
